# Generated by Django 4.2.3 on 2025-08-04 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("Masculin", "Masculin"), ("Féminin", "Féminin")],
                        max_length=10,
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("numero_telephone", models.CharField(max_length=20)),
                (
                    "departement",
                    models.CharField(
                        choices=[
                            ("SMQ", "SMQ"),
                            ("Ressources humaines", "Ressources humaines"),
                            ("Logistique", "Logistique"),
                            ("Ventes", "Ventes"),
                            ("Relations clients", "Relations clients"),
                        ],
                        default="SMQ",
                        max_length=50,
                    ),
                ),
                (
                    "plain_password",
                    models.CharField(
                        help_text="Mot de passe en clair pour affichage interne",
                        max_length=128,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
