# Generated by Django 4.2.3 on 2025-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMQ", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="identifiant",
            field=models.CharField(default="", max_length=128),
        ),
    ]
