# Generated by Django 4.2.3 on 2025-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMQ", "0002_userprofile_identifiant"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "departement",
                    models.CharField(
                        choices=[
                            ("Ressources humaines", "Ressources humaines"),
                            ("Garage", "Garage"),
                            ("Ventes", "Ventes"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "periode",
                    models.DateField(help_text="Premier jour du mois du rapport"),
                ),
                ("historique_de", models.DateField(blank=True, null=True)),
                ("historique_a", models.DateField(blank=True, null=True)),
                ("commentaires", models.TextField(blank=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="rapports_kpi/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="departement",
            field=models.CharField(
                choices=[
                    ("Ressources humaines", "Ressources humaines"),
                    ("Garage", "Garage"),
                    ("Ventes", "Ventes"),
                ],
                default="SMQ",
                max_length=50,
            ),
        ),
    ]
