# Generated by Django 4.2.3 on 2025-08-11 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("formule", models.TextField(blank=True, null=True)),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("Mensuelle", "Mensuelle"),
                            ("Trimestrielle", "Trimestrielle"),
                            ("Semestrielle", "Semestrielle"),
                            ("Annuelle", "Annuelle"),
                        ],
                        default="Mensuelle",
                        max_length=20,
                    ),
                ),
                (
                    "departement",
                    models.CharField(
                        choices=[
                            ("Ressources humaines", "Ressources humaines"),
                            ("Logistique", "Logistique"),
                            ("Ventes", "Ventes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("periode_annee", models.PositiveSmallIntegerField()),
                (
                    "periode_mois",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 signifie pas de mois, sinon 1-12"
                    ),
                ),
                ("valeur_cible", models.CharField(max_length=100)),
                ("date_soumission", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "soumis_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpis_soumis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nom", "-periode_annee", "-periode_mois"],
                "unique_together": {
                    ("nom", "departement", "periode_annee", "periode_mois")
                },
            },
        ),
        migrations.CreateModel(
            name="KPISubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.CharField(blank=True, max_length=255, null=True)),
                ("periode_annee", models.PositiveSmallIntegerField()),
                (
                    "periode_mois",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 signifie pas de mois, sinon 1-12"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manuel", "Saisie manuelle"),
                            ("fichier", "Fichier uploadé"),
                            ("base", "Source base de données"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        help_text="Fichier temporaire uploadé pour extraction de données. Le fichier n’est pas conservé durablement.",
                        null=True,
                        upload_to="kpi_submissions/",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Validée", "Validée"),
                            ("Rejetée", "Rejetée"),
                        ],
                        default="En attente",
                        max_length=20,
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to="Departement.kpi",
                    ),
                ),
                (
                    "soumis_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpis_soumissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_soumission"],
                "indexes": [
                    models.Index(
                        fields=["kpi", "periode_annee", "periode_mois"],
                        name="Departement_kpi_id_bd45fe_idx",
                    )
                ],
            },
        ),
    ]
