# Generated by Django 4.2.3 on 2025-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manuel", "Saisie manuelle"),
                    ("fichier", "Fichier uploadé"),
                    ("base", "Source base de données"),
                ],
                default="manuel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="departement",
            field=models.CharField(
                choices=[
                    ("Ressources humaines", "Ressources humaines"),
                    ("Garage", "Garage"),
                    ("Ventes", "Ventes"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="periode_mois",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0 = pas de mois, sinon 1-12"
            ),
        ),
        migrations.AlterField(
            model_name="kpisubmission",
            name="fichier",
            field=models.FileField(
                blank=True,
                help_text="Fichier temporaire pour extraction. Non conservé durablement.",
                null=True,
                upload_to="kpi_submissions/",
            ),
        ),
        migrations.AlterField(
            model_name="kpisubmission",
            name="periode_mois",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0 = pas de mois, sinon 1-12"
            ),
        ),
        migrations.AlterField(
            model_name="kpisubmission",
            name="source_type",
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
