# Generated by Django 4.2.3 on 2025-08-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Departement", "0002_kpi_source_type_alter_kpi_departement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpisubmission",
            name="fichier",
        ),
    ]
