# Generated by Django 4.2.3 on 2025-08-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Departement", "0003_remove_kpisubmission_fichier"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="kpisubmission",
            name="Departement_kpi_id_bd45fe_idx",
        ),
        migrations.AddField(
            model_name="kpisubmission",
            name="facteurs_utilises",
            field=models.JSONField(
                blank=True,
                help_text="Facteurs utilisés pour le calcul du KPI",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kpisubmission",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kpisubmission",
            name="soumis_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="kpisubmission",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manuel", "Saisie manuelle"),
                    ("fichier", "Fichier uploadé"),
                    ("base", "Source base de données"),
                ],
                default="manuel",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpisubmission",
            unique_together={("kpi", "periode_annee", "periode_mois", "soumis_par")},
        ),
    ]
