# Generated by Django 4.2.3 on 2025-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Departement",
            "0004_remove_kpisubmission_departement_kpi_id_bd45fe_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="formule_mathjax",
            field=models.CharField(default="", max_length=1024, null=True),
        ),
    ]
